name: test-task-kucoin
version: '3.8'

services:
  coin-db:
    container_name: coin-db
    image: postgres:16.1
    restart: always
    networks:
      - test-task-kucoin
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  tickers-service:
    build:
      context: ./tickers-service
      dockerfile: Dockerfile
      target: '${NODE_ENV}'
    container_name: 'tickers-service_${NODE_ENV}'
    entrypoint: ['npm', 'run', 'start:${NODE_ENV}-docker']
    environment:
      - NODE_ENV:${NODE_ENV}
    env_file:
      - ./tickers-service/.env
    depends_on:
      - coin-db
    volumes:
      - ./tickers-service:/usr/src/app/tickers-service
      - /usr/src/app/tickers-service/node_modules
    restart: unless-stopped
    networks:
      - test-task-kucoin

volumes:
  postgres:
    name: coin-db
  tickers-service:
    name: tickers-service

networks:
  test-task-kucoin:
    driver: bridge
